 const stats = [
  { name: "Avg Offline (yd)", value: "12.3 yds" },
  { name: "Miss Tendency", value: "67% Right" },
  { name: "Consistency", value: "8.7 yds" },
  { name: "Shots Tracked", value: "287" },
  { name: "Smash Factor", value: "1.48" },
  { name: "Ball Speed (mph)", value: "130" },
  { name: "Carry Distance (yd)", value: "180" },
  { name: "Total Distance (yd)", value: "195" },
  { name: "Launch Angle (°)", value: "13.5" },
  { name: "Attack Angle (°)", value: "-2.5" },
  { name: "Back Spin (rpm)", value: "3200" },
  { name: "Side Spin (rpm)", value: "200" },
  { name: "Face Angle (°)", value: "-1.8" },
  { name: "Club Path (°)", value: "0.5" },
  { name: "Launch Direction (°)", value: "1.2" },
  { name: "Spin Rate (rpm)", value: "3400" },
  { name: "Spin Axis (°)", value: "-3.0" },
  { name: "Landing Angle (°)", value: "42" },
  { name: "Dynamic Loft (°)", value: "18.5" },
  { name: "Apex Height (yd)", value: "45" },
  { name: "Shot Height (yd)", value: "44" },
  { name: "Face to Path (°)", value: "-2.3" },
  { name: "Shot Dispersion (yd)", value: "7.5" },
  { name: "Shot Shape Bias", value: "60% Draw" },
];

export default stats;