import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "../styles/globals.scss";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Swinga",
  description: "Generated by create next app",
};

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable}`}>
        <ThemeProvider attribute="data-theme" defaultTheme="light" enableSystem>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
